# Generated by Django 5.2.4 on 2025-07-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="max_players",
            field=models.IntegerField(choices=[(2, 2), (3, 3)], default=2),
        ),
        migrations.AddField(
            model_name="player",
            name="name",
            field=models.CharField(default="John", max_length=20),
        ),
    ]
