# Generated by Django 5.2.4 on 2025-07-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_game_is_private_game_max_players_player_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="max_players",
        ),
    ]
