# Generated by Django 5.2.4 on 2025-08-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_remove_game_max_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="turn",
            field=models.BooleanField(default=False),
        ),
    ]
