# Generated by Django 5.2.4 on 2025-08-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_player_turn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="winner",
        ),
    ]
