# Generated by Django 5.2.4 on 2025-08-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_remove_game_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="player",
            name="is_connected",
        ),
        migrations.RemoveField(
            model_name="player",
            name="joined_at",
        ),
    ]
