# Generated by Django 5.2.4 on 2025-08-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_remove_game_created_at_remove_player_is_connected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="last_move_made_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
